Repository AZDOPS/AZDOPS, pull requests merged in 2022-02, with the labels that each got.

#30 New function `New-AZDevOPSProject`
  .gitignore
  Source/AZDevOPS.psd1
  Source/Public/New-AZDevOPSProject.ps1
  Tests/New-AZDevOPSProject.tests.ps1
Labels: new function

#37 Added function Get-AzDevOPSProject
  Source/AZDevOPS.psd1
  Source/Public/Get-AzDevOPSProject.ps1
Labels: new function

#38 Added function New-AzDevOPSVariableGroup
  Source/AZDevOPS.psd1
  Source/Public/New-AzDevOPSVariableGroup.ps1
Labels: new function

#52 Added support for passing hash table to New-AZDOPSVariableGroup
  Source/Public/New-AZDOPSVariableGroup.ps1
Labels: new function

#74 add Function New-ADOPSPipeline Tests and Docs.
  Docs/Help/New-ADOPSPipeline.md
  Source/Public/New-ADOPSPipeline.ps1
  Tests/New-ADOPSPipeline.Tests.ps1
Labels: new function

#86 Updated hashtable and added tests
  Source/ADOPS.psd1
  Source/Public/New-ADOPSVariableGroup.ps1
  Tests/New-ADOPSVariableGroup.Tests.ps1
Labels: enhancement

#89 Added documentation
  Docs/Help/New-ADOPSVariableGroup.md
  Source/Public/New-ADOPSVariableGroup.ps1
Labels: documentation
